apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ValentinIgoufe/gitops
    targetRevision: HEAD
    path: cluster-config/appofapps
    directory:
      include: 'infrastructure/*.yaml'
      recurse: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
