apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-parent-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/ValentinIgoufe/gitops
    targetRevision: HEAD
    path: cluster-config/appofapps/monitoring
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
