apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-infrastructure
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/ValentinIgoufe/gitops
    targetRevision: HEAD
    path: cluster-config/appofapps/infrastructure
    directory:
      recurse: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
