apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ValentinIgoufe/gitops
    targetRevision: HEAD
    path: apps/guestbook/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook-frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true