apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-{{ .Values.appName }}-monitor
  namespace: {{ index  .Values "prometheus-stack" "namespace" }}
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.appName }}
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      scrapeTimeout: 10s