# guestbook-chart/values.yaml

frontend: 
  replicaCount: 1
  image: valouche190705/guestbook:v0.0.3
  namespace: guestbook-frontend
  appName: guestbook-frontend

backend:
  replicaCount: 1
  image: valouche190705/guestbook:v0.0.3
  namespace: guestbook-backend
  appName: guestbook-backend