apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kubernetes-alerts
  namespace: {{ index  .Values "prometheus-stack" "namespace" }}
  labels:
    release: {{ .Release.Name }}
spec:
  groups:
    - name: kubernetes.rules
      rules:
        - alert: PodCrashLooping
          expr: rate(kube_pod_container_status_restarts_total[15m]) > 0
          for: 5m
          labels:
            severity: warning
          annotations:
            {{- raw }}
            summary: "Pod {{ $labels.pod }} redémarre fréquemment"
            description: "Le pod {{ $labels.pod }} dans {{ $labels.namespace }} a redémarré {{ $value }} fois."
            {{- endraw }}
        
        - alert: HighMemoryUsage
          expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) > 0.9
          for: 5m
          labels:
            severity: critical
          annotations:
            {{- raw }}
            summary: "Utilisation mémoire critique"
            description: "Le conteneur {{ $labels.container }} utilise plus de 90% de sa limite mémoire."
            {{- endraw }}