apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.frontend.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.backend.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.monitoring.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"