apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ValentinIgoufe/gitops
    path: cluster-config/appofapps/infrastructure/linkerd/control
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true