apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-{{ .Values.appName }}-monitor
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      monitoring: {{ .Values.global.monitoring.labels.monitoring }}
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      scrapeTimeout: 10s