apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-{{ .Values.appName }}-vpa
  namespace: {{ .Values.namespace }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ .Release.Name }}-{{ .Values.appName }}-deployment
  updatePolicy:
    updateMode: "Off" 