apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guestbook-ingress
  namespace: guestbook-backend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: guestbook.127.0.0.1.nip.io
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: guestbook-backend-service
            port:
              number: 80