apiVersion: v2
name: monitoring-chart
description: A Helm chart for Prometheus, Grafana and AlertManager

type: application

version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: kube-prometheus-stack
    version: "84.0.0" 
    repository: "https://prometheus-community.github.io/helm-charts"
    alias: prometheusStack
    condition: prometheusStack.enabled
